def Reporte_Lista(name, claves, registro):
    file = open("reportes/" + name + ".html", "w")
    file.write("<!DOCTYPE html>")
    file.write("<head>")
    file.write("<meta charset=\"UTF-8\">")
    file.write("<title> Reporte_Lista </title>")
    file.write(
        "<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\">")
    file.write(
        "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilo.css\">")
    file.write("<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimum-scale=1.0\">")
    file.write("</head>")
    file.write("<body>")
    file.write("<div class=\"contenedor\">")
    file.write("<header id=\"hd\">")
    file.writelines("<center>")
    file.writelines("<h3 style=\"color: white;\">"+name+"</h3>")
    file.writelines("</center>")
    file.write("</header>")
    file.write("<section class=\"main\">")
    file.write("<table class=\"table table-hover table-bordered table-dark table-sm\">")
    
    file.write("<thead class=\"thead-light\">")
    file.writelines("<tr>")
    for clave in claves:
        file.writelines("<th>"+clave+"</th>")
    file.writelines("</tr>")
    file.write("</thead>")
    
    for i in range(0, len(registro)):
        file.writelines("<tr>")
        for j in range (0, len(registro[0])):
            file.writelines("<th>"+ registro[i][j]+"</th>")
        file.writelines("</tr>")

    file.write("</table>")
    file.write("<footer>")
    file.write("<p>")
    file.writelines("<h5>&copy 202001053</h5>")
    file.write("</p>")
    file.write("</footer>")
    file.write("</div>")
    file.write("</body>")
    file.write("</html>")
    file.close()

def Tokens_report(tokens):
    file = open("reportes/tokens_reporte.html", "w")
    file.write("<!DOCTYPE html>")
    file.write("<head>")
    file.write("<meta charset=\"UTF-8\">")
    file.write("<title> Reporte_Tokens </title>")
    file.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\">")
    file.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilo.css\">")
    file.write("<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimum-scale=1.0\">")
    file.write("</head>")
    file.write("<body>")
    file.write("<div class=\"contenedor\">")
    file.write("<header id=\"hdd\">")
    file.write("<img src=\"img/reporte.png\" id=\"logo\">")
    file.write("</header>")
    file.write("<section class=\"main\">")
    file.write("<table class=\"table table-hover table-bordered table-dark table-sm\">")
    file.write("<thead class=\"thead-light\">")
    file.write("<tr>")
    file.write("<th>Lexema</th>")
    file.write("<th>Token</th>")
    file.write("<th>Fila</th>")
    file.write("<th>Columna</th>")
    file.write("</tr>")
    file.write("</thead>")

    for token in tokens:
        file.writelines("<tr>")
        file.writelines("<th>"+token.lexema+"</th>")
        file.writelines("<th>"+token.tipo+"</th>")
        file.writelines("<th>"+str(token.linea)+"</th>")
        file.writelines("<th>"+str(token.columna)+"</th>")
        file.writelines("</tr>")
           
    file.write("</table>")
    file.write("<footer>")
    file.write("<p>")
    file.writelines("<h5>&copy 202001053</h5>")
    file.write("</p>")
    file.write("</footer>")
    file.write("</div>")
    file.write("</body>")
    file.write("</html>")
    file.close()



def Errors_report(errores, name):
    file = open("reportes/"+name+".html", "w")
    file.write("<!DOCTYPE html>")
    file.write("<head>")
    file.write("<meta charset=\"UTF-8\">")
    file.write("<title> Reporte_Errores </title>")
    file.write(
        "<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\">")
    file.write(
        "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilo.css\">")
    file.write("<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimum-scale=1.0\">")
    file.write("</head>")
    file.write("<body>")
    file.write("<div class=\"contenedor\">")
    file.write("<header id=\"hdd\">")
    file.write("<img src=\"img/reporte.png\" id=\"logo\">")
    file.write("</header>")
    file.write("<section class=\"main\">")
    file.write(
        "<table class=\"table table-hover table-bordered table-dark table-sm\">")
    file.write("<thead class=\"thead-light\">")
    file.write("<tr>")
    file.write("<th>Descripcion</th>")
    file.write("<th>Fila</th>")
    file.write("<th>Columna</th>")
    file.write("</tr>")
    file.write("</thead>")

    for error in errores:
        file.writelines("<tr>")
        file.writelines("<th>"+error.descripcion+"</th>")
        file.writelines("<th>"+str(error.linea)+"</th>")
        file.writelines("<th>"+str(error.columna)+"</th>")
        file.writelines("</tr>")

    file.write("</table>")
    file.write("<footer>")
    file.write("<p>")
    file.writelines("<h5>&copy 202001053</h5>")
    file.write("</p>")
    file.write("</footer>")
    file.write("</div>")
    file.write("</body>")
    file.write("</html>")
    file.close()


def Errors_report_Sintact(bugs, name):
    file = open("reportes/"+name+".html", "w")
    file.write("<!DOCTYPE html>")
    file.write("<head>")
    file.write("<meta charset=\"UTF-8\">")
    file.write("<title> Reporte_Errores </title>")
    file.write(
        "<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\">")
    file.write(
        "<link rel=\"stylesheet\" type=\"text/css\" href=\"css/estilo.css\">")
    file.write("<meta name=\"viewport\" content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximun-scale=1.0, minimum-scale=1.0\">")
    file.write("</head>")
    file.write("<body>")
    file.write("<div class=\"contenedor\">")
    file.write("<header id=\"hdd\">")
    file.write("<img src=\"img/reporte.png\" id=\"logo\">")
    file.write("</header>")
    file.write("<section class=\"main\">")
    file.write(
        "<table class=\"table table-hover table-bordered table-dark table-sm\">")
    file.write("<thead class=\"thead-light\">")
    file.write("<tr>")
    file.write("<th>Descripcion</th>")
    file.write("</tr>")
    file.write("</thead>")

    for bug in bugs:
        file.writelines("<tr>")
        file.writelines("<th>"+bug+"</th>")
        file.writelines("</tr>")

    file.write("</table>")
    file.write("<footer>")
    file.write("<p>")
    file.writelines("<h5>&copy 202001053</h5>")
    file.write("</p>")
    file.write("</footer>")
    file.write("</div>")
    file.write("</body>")
    file.write("</html>")
    file.close()
